### ISSUE TITLE
./py4web.py run apps - OSError: [Errno 98] Address already in use

### ISSUE THREAD

**Issue by RichardBH** [tomcam/py4webcasts#6]
You don't need to do this to run it. But it is a good test. You will always get an OSError: [Errno 98] Address already in use error. (We need to mention that you will get this error and to ignore it.)

Start py4web
Return to the PythonAnywhere bash shell.
Start py4web like so:
$ ./py4web.py run apps
This starts the built-in py4web web server and runs its own copy of the py4web site. It is now available online at your PythonAnywhere URL.

03:31 ~/py4web (master)$ ./py4web.py run apps

██████╗ ██╗   ██╗██╗  ██╗██╗    ██╗███████╗██████╗
██╔══██╗╚██╗ ██╔╝██║  ██║██║    ██║██╔════╝██╔══██╗
██████╔╝ ╚████╔╝ ███████║██║ █╗ ██║█████╗  ██████╔╝
██╔═══╝   ╚██╔╝  ╚════██║██║███╗██║██╔══╝  ██╔══██╗
██║        ██║        ██║╚███╔███╔╝███████╗██████╔╝
╚═╝        ╚═╝        ╚═╝ ╚══╝╚══╝ ╚══════╝╚═════╝
Is still experimental...
Py4web: 1.20200905.1 on Python 3.8.0 (default, Nov 14 2019, 22:29:45) 
[GCC 5.4.0 20160609]
Dashboard is at: http://127.0.0.1:8000/_dashboard
[X] loaded todo       
[X] loaded myfeed       
[X] loaded _documentation       
[X] loaded _minimal       
[X] loaded _dashboard       
[X] loaded _scaffold       
[X] loaded examples       
[X] loaded _default       
Bottle v0.12.17 server starting up (using TornadoServer())...
Listening on http://127.0.0.1:8000/
Hit Ctrl-C to quit.
Traceback (most recent call last):
  File "./py4web.py", line 5, in <module>
    cli()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/rbehanhowell/py4web/py4web/core.py", line 1512, in run
    start_server(args)
  File "/home/rbehanhowell/py4web/py4web/core.py", line 1245, in start_server
    bottle.run(**params)
  File "/usr/lib/python3.8/site-packages/bottle.py", line 3131, in run
    server.run(app)
  File "/usr/lib/python3.8/site-packages/bottle.py", line 2862, in run
    server.listen(port=self.port,address=self.host)
  File "/usr/lib/python3.8/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/lib/python3.8/site-packages/tornado/netutil.py", line 174, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 98] Address already in use

**Comment by jparga** [comment]
In a Linux System this worked for me:

sudo kill $(sudo lsof -t -i:8000)

It kills the previous process running in port 8000
